channels:
- conda-forge
dependencies:
- python=3.12.3
- pip=23.2.1
- nodejs=22.11.0
- pip:
  - robotframework==7.2
  - robotframework-browser==19.3
  - alumnium
  - alumnirobot
  - faker
  - robotcode-runner

rccPostInstall:
- rfbrowser init